name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --release
  build:
    runs-on: ubuntu-latest
    if: github.event == 'release'
    depends-on: 
      - test
    matrix:
      target:
        - x86_64-unknown-linux-musl
        - aarch64-unknown-linux-musl
        - mipsel-unknown-linux-musl
    steps:
    - uses: actions/checkout@v3
    - name: Install cross
      run: cargo install cross
    - name: Build
      run: cross build --release
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: gz
        GHR_PATH: target/${{ matrix.target }}/release/sshmultiplexer-rust
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
