name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test
      - name: Build
        run: cargo build
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - mipsel-unknown-linux-musl
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.target }}
      - name: Install cross
        run: cargo install cross
      - name: Build
        run: |
          cross build --target=${{ matrix.target }} --release && \
            mv -v target/${{ matrix.target }}/release/sshmultiplexer-rust \
              sshmultiplexer-rust.${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: sshmultiplexer-rust.${{ matrix.target }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v3
      - name: Upload release asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload \
            ${{ github.ref_name }} \
            */sshmultiplexer-rust.*

    
